fix: docker compose command to me with space, not dash

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -65,18 +65,16 @@ jobs:
         run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
       - name: Deploy via SSH
         uses: appleboy/ssh-action@v0.1.7
-        env:
-          VERSION: ${{ env.VERSION }}
         with:
+          envs: VERSION
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-            cd /deploy/github-banners/
-            export VER=$VERSION
-            docker-compose -f docker-compose.prod.yaml pull
-            docker-compose -f docker-compose.prod.yaml up -d
+            cd ~/deploy/github-banners/
+            VER=$VERSION docker compose -f docker-compose.prod.yaml pull
+            VER=$VERSION docker compose -f docker-compose.prod.yaml up -d --build
   health-check:
     runs-on: ubuntu-latest
     needs: deploy
@@ -84,10 +82,11 @@ jobs:
     steps:
       - name: http preview endpoint check
         run: |
-          curl -o /dev/null -s -w "%{http_code}" "https://$DOMAIN/banners/preview?username=hurtki&type=dark" | grep -q "^200$"
+          response=$(curl -si "https://${{ secrets.DOMAIN }}/banners/preview?username=hurtki&type=dark")
+          echo "$response" | grep -q "^HTTP.*200" || { echo "❌ banner preview failed:"$'\n'"$response"; exit 1; }
   rollback:
     needs: health-check
-    if: needs.health-check.result == 'failure'
+    if: ${{ always() && needs.health-check.result == 'failure' }}
     runs-on: ubuntu-latest
     environment: ssh-deploy
     steps:
@@ -96,19 +95,19 @@ jobs:
           fetch-depth: 0
       - name: Get previous version
         run: |
-          PREV_TAG=$(git tag --sort=-creatordate | sed -n \'2p\' | sed \'s/^v//\')
+          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' | sed 's/^v//')
           echo "PREV_VERSION=${PREV_TAG}" >> $GITHUB_ENV
       - name: Rollback via ssh
         uses: appleboy/ssh-action@v0.1.7
         env:
           VERSION: ${{ env.PREV_VERSION }}
         with:
+          envs: PREV_VERSION
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-            cd /deploy/github-banners/
-            export VER=$VERSION
-            docker-compose -f docker-compose.prod.yaml pull
-            docker-compose -f docker-compose.prod.yaml up -d
+            cd ~/deploy/github-banners/
+            VER=$PREV_VERSION docker compose -f docker-compose.prod.yaml pull
+            VER=$PREV_VERSION docker compose -f docker-compose.prod.yaml up -d --build
